### ISSUE TITLE
Debian 9: /var/lib/apt/periodic/update-success-stamp not found

### ISSUE THREAD

**Issue by clecherbauer** [pmaene/apt_exporter#1]
I tried to run apt_exporter on Debian 9 and got this exception:

Jan 19 21:05:45 apt_exporter[15566]: time="2020-01-19T21:05:45+01:00" level=fatal msg="no such file or directory" source="apt_exporter.go:359"

I think this is the cause:
https://github.com/pmaene/apt_exporter/blob/4aecd1ef994817bb3f882c635a599210220b340c/apt_exporter.go#L244

Directly after a new installation of Debian the /var/lib/apt/periodic directory is empty.
Maybe these files are firstly written after the execution of the APT Periodic cron.  Furthermore the file /var/lib/apt/periodic/update-success-stamp is named /var/lib/apt/periodic/udate-stamp.

For which distribution did you develop this exporter?

**Comment by pmaene** [comment]
Hi! Thanks for checking this out, that's nice to see! I've built this exporter for Ubuntu and never tried it on Debian (let alone a fresh installation), so I'm not surprised to see it failing.

Given that it gets this far, I assume this means ``/var/log/apt/history.log`` does exist on Debian? Do you know if it creates ``/var/lib/apt/periodic/update-success-stamp`` at some point, or if it has a similar file. I added these watchers with out-of-band updating to avoid having the ``apt`` calls during the HTTP endpoint, as they are rather slow.

**Comment by pmaene** [comment]
@lebokus Would you mind trying again with the version I just pushed (v0.3.0). I believe both issues should have been addressed (the file not existing, and the different name of the stamp file on Debian).

**Comment by clecherbauer** [comment]
Sorry for not responding - I will test it tonight.

Thank you very much!

**Comment by clecherbauer** [comment]
@pmaene Yeah this fixed it. Thanks for your effort :)

**Comment by pmaene** [comment]
Great, happy to hear that! Thank you for checking!
